runtime: nodejs16
entrypoint: npm run start:prod
service: $APPENGINE_SERVICE_NAME
instance_class: B2
env_variables:
  NODE_ENV: production
  DB_SOCKET_PATH: /cloudsql/$CLOUDSQL_CONN_NAME
  DB_USER: $CLOUDSQL_USERNAME
  DB_PASSWORD: $CLOUDSQL_PASSWORD
  DB_NAME: $CLOUDSQL_DB_NAME
  DB_MIGRATIONS_RUN: true
basic_scaling:
  max_instances: 1
  idle_timeout: 30m
