name: deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  appengine:
    name: app engine
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        id: auth
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Replace database secrets and other placeholders
        run: |
          sed -i 's/$CLOUDSQL_USERNAME/${{ secrets.CLOUDSQL_USERNAME }}/g' app.yaml
          sed -i 's/$CLOUDSQL_PASSWORD/${{ secrets.CLOUDSQL_PASSWORD }}/g' app.yaml
          sed -i 's/$CLOUDSQL_CONN_NAME/${{ secrets.CLOUDSQL_CONN_NAME }}/g' app.yaml
          sed -i 's/$CLOUDSQL_DB_NAME/${{ secrets.CLOUDSQL_DB_NAME }}-${{ github.ref_name == 'main' && 'prod' || 'staging' }}/g' app.yaml
          sed -i 's/$APPENGINE_SERVICE_NAME/nest-${{ github.ref_name == 'main' && 'prod' || 'staging' }}/g' app.yaml
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to App Engine
        run: |
          cp app.yaml dist/
          cd dist/
          gcloud app deploy --quiet
